name: workout
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aligned_dialog: 0.0.6
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  cloud_firestore: 4.8.0
  cloud_firestore_platform_interface: 5.15.0
  cloud_firestore_web: 3.6.0
  dropdown_button2: 2.3.9
  file_picker: 6.1.1
  firebase_auth: 4.6.2
  firebase_auth_platform_interface: 6.15.2
  firebase_auth_web: 5.5.2
  firebase_core: 2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: 2.5.0
  firebase_performance: 0.9.2+2
  firebase_performance_platform_interface: 0.1.4+2
  firebase_performance_web: 0.1.4+2
  firebase_storage: 11.2.2
  firebase_storage_platform_interface: 4.4.2
  firebase_storage_web: 3.6.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl: 0.18.1
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.6
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stream_transform: 2.1.0
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.8.1
  video_player_android: 2.4.10
  video_player_avfoundation: 2.5.1
  video_player_platform_interface: 6.2.1
  video_player_web: 2.1.2
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  timer_count_down: ^2.2.0
  assets_audio_player: ^3.1.1
  camera: ^0.10.5+9
  flutter_local_notifications: ^9.6.1


  google_ml_kit_jumping_jack:
    path: ../pose-warmup/01-flutter-ml-kit-pose-plugin-jumping-jack
  google_ml_kit_toy_soldier:
    path: ../pose-warmup/02-flutter-ml-kit-pose-plugin-toy-soldier
  google_ml_kit_high_knees:
    path: ../pose-warmup/03-flutter-ml-kit-pose-plugin-high-knees
  google_ml_kit_balance_arm_swing:
    path: ../pose-warmup/04-flutter-ml-kit-pose-plugin-balance-arm-swing
  google_ml_kit_arm_circles:
    path: ../pose-warmup/05-flutter-ml-kit-pose-plugin-arm-circles
  google_ml_kit_push_up:
    path: ../arm&chest/06-flutter-ml-kit-pose-plugin-push-up
  google_ml_kit_knee_push_up:
    path: ../arm&chest/07-flutter-ml-kit-pose-plugin-knee-push-up
  google_ml_kit_box_push_up:
    path: ../arm&chest/08-flutter-ml-kit-pose-plugin-box-push-up
  google_ml_kit_shoulder_stretch:
    path: ../arm&chest/09-flutter-ml-kit-pose-plugin-shoulder-stretch
  google_ml_kit_cobra_stretch:
    path: ../arm&chest/10-flutter-ml-kit-pose-plugin-cobra-stretch
  google_ml_kit_abdominal_crunch:
    path: ../abs/11-flutter-ml-kit-pose-plugin-abdominal-crunch
  google_ml_kit_legs_raise:
    path: ../abs/12-flutter-ml-kit-pose-plugin-legs-raise
  google_ml_kit_plank:
    path: ../abs/13-flutter-ml-kit-pose-plugin-plank
  google_ml_kit_mountain_climber:
    path: ../abs/14-flutter-ml-kit-pose-plugin-mountain-climber
  google_ml_kit_sit_up:
    path: ../abs/15-flutter-ml-kit-pose-plugin-sit-up
  google_ml_kit_arm_raises:
    path: ../shoulder&back/16-flutter-ml-kit-pose-plugin-arm-raises
  google_ml_kit_tricep_kickback:
    path: ../shoulder&back/17-flutter-ml-kit-pose-plugin-tricep-kickback
  google_ml_kit_side_arm_raises:
    path: ../shoulder&back/18-flutter-ml-kit-pose-plugin-side-arm-raises
  google_ml_kit_sidelying_floor_stretch:
    path: ../shoulder&back/19-flutter-ml-kit-pose-plugin-sidelying-floor-stretch
  google_ml_kit_cat_cow_pose:
    path: ../shoulder&back/20-flutter-ml-kit-pose-plugin-cat-cow-pose
  google_ml_kit_lunches:
    path: ../leg/21-flutter-ml-kit-pose-plugin-lunches
  google_ml_kit_squats:
    path: ../leg/22-flutter-ml-kit-pose-plugin-squats
  google_ml_kit_sidelying_leg_raises:
    path: ../leg/23-flutter-ml-kit-pose-plugin-sidelying-leg-raises
  google_ml_kit_donkey_kick:
    path: ../leg/24-flutter-ml-kit-pose-plugin-donkey-kick
  google_ml_kit_quad_stretch_with_wall:
    path: ../leg/25-flutter-ml-kit-pose-plugin-quad-stretch-with-wall

  timezone: ^0.8.0
  syncfusion_flutter_charts: ^24.2.4+3
  syncfusion_flutter_datepicker: ^24.2.4
  image: ^4.1.7
  firebase_database: ^10.2.2
  
  #timezone: ^0.9.2

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:

  image_path: "assets/iconapp.jpg"
  android: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

    

    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  
 
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
